config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'homepage#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :deals
  match 'buy_now' => 'homepage#handle_buy_now', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  require "active_storage"
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
  include ValidDeal

  has_one_attached :image # Used ActiveRecord Storage for Image Upload
  has_one :user_deal

  validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i } # Checks Presence of all the fields except id, created_at, and updated_at
  validates_uniqueness_of :publish_date

  def self.todays_deal
    deals = Deal.where(publish_date: Date.today.to_s ).or(Deal.where(publish_date: Date.yesterday.to_s)) # Yesterday deals must be available for today upto 10:00 am

    return if deals.empty?

    valid_deal = nil
    deals.each do |deal|
      valid_deal = ValidDeal::is_valid_deal(deal)
    end
    valid_deal
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_deals
end

app/models/user_deal.rb
class UserDeal < ApplicationRecord
  belongs_to :user
  belongs_to :deal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  layout "admin"
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :description, :price, :discounted_price, :quantity, :publish_date, :image)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  include ValidDeal

  def index
    @deal = Deal.todays_deal
    @user_deal = UserDeal.where(user_id: current_user.id, deal_id: @deal.id).first if @deal
  end

  def handle_buy_now
    @deal = Deal.find(params[:deal_id])

    if ValidDeal::is_valid_deal(@deal)
      user_deal = UserDeal.where(user_id: current_user.id, deal_id: @deal.id).first_or_create
      user_deal.quantity += 1 # params[:quantity] for more than 1 quantity

      respond_to do |format|
        if user_deal.save!
          @deal.quantity -= 1
          @deal.save!
          format.html { redirect_to '/', notice: 'Congratulations, You have successfully purchased the deal.' }
        else
          format.html { redirect_to '/', notice: 'Sorry, Something went wrong' }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to '/', notice: 'Sorry, This Deal has expired' }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper

  def calc_discounted_price(total_amount, discount_percent )
    return total_amount if discount_percent.zero?

    calc_discount_percent = discount_percent < 6 ? discount_percent : 5
    (total_amount - (total_amount * 0.01 * calc_discount_percent)).to_i
  end

end

app/views/deals/_form.html.erb
<%= form_with(model: deal, local: true) do |form| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :discounted_price %>
    <%= form.number_field :discounted_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<div class="m-auto">

  <div class="h5 mb-3">EDIT DEALS
    <div class="float-right">
      <%= link_to 'Show', @deal %> |
      <%= link_to 'Back', deals_path %>
    </div>
  </div>

  <%= render 'form', deal: @deal %>

</div>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deals</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Discounted price</th>
      <th>Quantity</th>
      <th>Publish date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.title %></td>
        <td><%= deal.description %></td>
        <td><%= deal.price %></td>
        <td><%= deal.discounted_price %></td>
        <td><%= deal.quantity %></td>
        <td><%= deal.publish_date %></td>
        <td>
          <% if deal.image.attached? %>
              <%= image_tag deal.image, height: 30, width: 30 %>
          <% end %>
        </td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<div class="m-auto">

  <div class="h5 mb-3">EDIT DEALS
    <div class="float-right">
      <%= link_to 'Back', deals_path %>
    </div>
  </div>

  <%= render 'form', deal: @deal %>
</div>

app/views/deals/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @deal.price %>
</p>

<p>
  <strong>Discounted price:</strong>
  <%= @deal.discounted_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @deal.quantity %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @deal.publish_date %>
</p>

<% if @deal.image.attached? %>
  <p>
    <strong>Image:</strong>
    <br>
    <%= image_tag @deal.image %>
  </p>
<% end %>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

app/views/homepage/index.html.erb
<h1 class="h1">Deal Of The Day</h1>

<% if @deal.present? %>

  <div class="card mt-2" style="width:200px">
    <h5 class="card-title text-center"><%= @deal.title %></h5>
    <% if @deal.image.attached? %>
        <%= image_tag @deal.image, class: "card-img-top" %>
    <% end %>
    <div class="card-body">
      <p class="card-text small"><b>Description: </b><%= @deal.description %></p>
      <p class="card-text small"><b>Price: </b><%= @deal.price %></p>
      <p class="card-text small"><b>Discounted Price: </b>
        <%=
          @user_deal.present? ?
          calc_discounted_price(@deal.discounted_price, @user_deal.quantity )
          : @deal.discounted_price
          %>
      </p>
      <p class="card-text small"><b>Deal Quantity: </b><%= @deal.quantity %></p>
      <p>
        <% if @deal.quantity.zero? %>
          Out Of Stock
        <% else %>
          <%= link_to 'Buy Now', url_for(action: "handle_buy_now", deal_id: @deal.id), data: { confirm: "Are you sure?" }, class: "btn btn-block btn-success text-light" %>
        <% end %>
      </p>
    </div>
  </div>
<% else %>
  <p>No Deals To Display</p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashSalesApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger notice"><%= alert %></p>
    <% end %>

    <div class="container"
      <%= yield %>
    </div>
  </body>
</html>

<script>
  setTimeout("$('.notice').fadeOut('slow')", 2000)
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashSalesApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger notice"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-expand-md navbar-light mb-3">
      <a class="navbar-brand" href="#">Flash Sales Logo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">HomePage</a>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <% if user_signed_in? %>
            <%#= current_user.email %>
            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container"
      <%= yield %>
    </div>
  </body>
</html>

<script>
  setTimeout("$('.notice').fadeOut('slow')", 2000)
</script>